services:
  postgres:
    image: postgres:18.2
    container_name: ${POSTGRES_CONTAINER}
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql

    networks:
      - n8n_default

volumes:
  career_postgres_data:
    name: ${POSTGRES_VOLUME}

networks:
  n8n_default:
    external: true
