services:
  mc:
    image: itzg/minecraft-server
    container_name: ghost-gaming-test
    ports:
      - "0.0.0.0:25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.11"
      MEMORY: 4G
      ENABLE_RCON: "true"
      ONLINE_MODE: "true"
    volumes:
      - ${MINECRAFT_DATA_PATH}:/data
    restart: unless-stopped
