apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: infra
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "kubernetes-pods"
        kubernetes_sd_configs:
          - role: pod

      - job_name: "node-exporter"
        static_configs:
          - targets: ${NODE_EXPORTER_TARGETS}

      - job_name: "cadvisor"
        static_configs:
          - targets: ${CADVISOR_TARGETS}

      - job_name: "kube-state-metrics"
        static_configs:
          - targets:
              - kube-state-metrics.infra.svc.cluster.local:8080

      - job_name: "k8s-node-exporter"
        static_configs:
          - targets: ${K8S_NODE_EXPORTER_TARGETS}

