apiVersion: apps/v1
kind: Deployment
metadata:
  name: syslog-ng
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syslog-ng
  template:
    metadata:
      labels:
        app: syslog-ng
    spec:
      containers:
        - name: syslog-ng
          image: balabit/syslog-ng:latest
          ports:
            - containerPort: 514
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /etc/syslog-ng
            - name: logs
              mountPath: /var/log/opnsense
      volumes:
        - name: config
          configMap:
            name: syslog-ng-config
        - name: logs
          persistentVolumeClaim:
            claimName: syslog-ng-logs-pvc
