apiVersion: apps/v1
kind: Deployment
metadata:
  name: lazylibrarian
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lazylibrarian
  template:
    metadata:
      labels:
        app: lazylibrarian
    spec:
      containers:
        - name: lazylibrarian
          image: lscr.io/linuxserver/lazylibrarian:latest
          ports:
            - containerPort: 5299
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: lazylibrarian-config-pvc
        - name: data
          persistentVolumeClaim:
            claimName: media-downloads-pvc
