apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lazylibrarian-ingress
  namespace: media
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod-cf
spec:
  ingressClassName: traefik
  tls:
    - hosts: [lazylibrarian.${BASE_DOMAIN}]
      secretName: lazylibrarian-tls-secret
  rules:
    - host: lazylibrarian.${BASE_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lazylibrarian-svc
                port:
                  number: 80
