apiVersion: v1
kind: ConfigMap
metadata:
  name: karakeep-config
  namespace: personal
data:
  TZ: "Australia/Sydney"

  LOG_LEVEL: "info"
  ENABLE_METRICS: "false"
  ENABLE_DEBUG: "false"

  MAX_UPLOAD_GB: "5"
