apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-config
  namespace: personal
data:
  PAPERLESS_URL: https://paperless.${BASE_DOMAIN}
  PAPERLESS_TIME_ZONE: Australia/Sydney
  PAPERLESS_OCR_LANGUAGE: eng
  PAPERLESS_REDIS: redis://paperless-redis:6379
  PAPERLESS_TIKA_ENABLED: "true"
  PAPERLESS_TIKA_ENDPOINT: http://paperless-tika:9998
  PAPERLESS_GOTENBERG_ENDPOINT: http://paperless-gotenberg:3000
  PAPERLESS_CONSUMER_POLLING: "1"
  PAPERLESS_FILENAME_FORMAT: "{document_type}/{created_year}/{title}"
  PAPERLESS_BIND_ADDR: 0.0.0.0
  PAPERLESS_PORT: "8000"
  PAPERLESS_MEDIA_ROOT: /usr/src/paperless/media
  PAPERLESS_CONSUMER_DIR: /usr/src/paperless/consume
  PAPERLESS_EXPORT_DIR: /usr/src/paperless/export
